CREATE TABLE BOARD
(NUM NUMBER(9) NOT NULL,
NAME VARCHAR2(20) NOT NULL,
PWD VARCHAR2(10) NOT NULL,
EMAIL VARCHAR2(50),
SUBJECT VARCHAR2(50) NOT NULL,
CONTENT VARCHAR2(4000) NOT NULL,
IPADDR VARCHAR2(20),
HITCOUNT NUMBER(9),
CREATED DATE,
CONSTRAINT PK_BOARD_NUM PRIMARY KEY(NUM));
 
SELECT * FROM BOARD;